# fly.toml app configuration file generated for render-webflow-restless-river-7629 on 2025-02-21T18:02:26-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'render-webflow-restless-river-7629'
primary_region = 'gdl'

[build]
  dockerfile = 'Dockerfile'

[env]
  DATABASE_URL = 'postgres://postgres:Z6jhZNBqF2wJovw@postgree-database.internal:5432'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
